import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { unstable_setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ["en", "gu"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

const RootLayout = ({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) => {
  unstable_setRequestLocale(locale);
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <div className="max-w-sm m-auto px-4">{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
